services:
  gateway:
    image: parthokr/heapdog:gateway-latest
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - USER_SERVICE_URI=${USER_SERVICE_URI:-http://user-service:8080}

    depends_on:
      - user-service

    networks:
      - heapdog-network

  user-service:
    image: parthokr/heapdog:user-service-dev-latest
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    networks:
      - heapdog-network
    depends_on:
      - db

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=heapdog
      - POSTGRES_PASSWORD=heapdogpassword
      - POSTGRES_DB=heapdogdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - heapdog-network

networks:
  heapdog-network:
    external: true